### PR TITLE
add device_type to csv import

### PR DESCRIPTION
**Pull request by ryanmerolle**
closes issue #46

### CODE REVIEW

**Comment by ryanmerolle** [comment]
I thought it was a simple add of the missing var.  I will investigate further.

**Comment by FragmentedPacket** [comment]
@ryanmerolle Did adding the `device_type` entry in the form not solve the issue or are you concerned about Travis CI not passing?

**Comment by dgarros** [comment]
@ryanmerolle right now TravisCI is failing because of `black`, please run `black .` locally to fix your code

**Comment by ryanmerolle** [comment]
Thanks @dgarros, that worked!

**Comment by dgarros** [comment]
@glennmatthews please can you take a look ?

**Pull request merged**
